name: Build and push GE-Proton based image
on: workflow_dispatch
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: date-tag
        id: docker-tag
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Build image
        id: buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: enshrouded-dedicated-server
          context: ./container/proton
          containerfiles: ./container/proton/Dockerfile
          tags: "${{ steps.docker-tag.outputs.tag }},latest"
      - name: Push image to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah.outputs.image }}
          tags: ${{ steps.buildah.outputs.tags }}
          registry: docker.io/${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
